const color = {
    btn_bg: "#fafbfc",
    btn_hover_bg: "#f3f4f6",
    btn_text: "#24292e",
    btn_primary_bg: "#2ea44f",
    btn_primary_hover_bg: "#2c974b",
    btn_primary_border: "rgba(27, 31, 35, 0.15)",
    btn_primary_shadow: "rgba(27, 31, 35, 0.04)",
    btn_primary_text: "#ffffff",
    loading_dots: "#d8d8d8",
    sidemenu_hover: "#2e9afe",
    sidemenu_default: "#6e6e6e",
    header_bg: "#24292e",
    header_title_text: "#ffffff",
    header_dropmenu_bg: "#ffffff",
    header_dropmenu_hover_bg: "#0366d6",
    header_dropmenu_text: "#1b1f23",
    header_dropmenu_hover_text: "#ffffff",
    header_dropmenu_boader: "#e1e4e8",
    header_dropmenu_modal_bg: "transparent",
    caret_text: "#ffffff",
    issue_drop_btn: "#6a737d",
    issue_drop_hover_btn: "#444d56",
    issue_drop_modal_bg: "transparent",
    issue_item_title: "#0366d6",
    issue_item_detail_info_text: "#6a737d",
    issue_item_milestone_title: "#6a737d",
    list_group_header_border: "#eaecef",
    list_group_header_bg: "#f6f8fa",
    list_group_item_bg: "#ffffff",
    list_group_item_hover_bg: "#f6f8fa",
    list_group_border: "#eaecef"
};

export { color };
