const color = {
    btn_bg: "#fafbfc",
    btn_hover_bg: "#f3f4f6",
    btn_text: "#24292e",
    btn_primary_bg: "#2ea44f",
    btn_primary_hover_bg: "#2c974b",
    btn_primary_border: "rgba(27, 31, 35, 0.15)",
    btn_primary_shadow: "rgba(27, 31, 35, 0.04)",
    btn_primary_text: "#ffffff",
    textarea_bg: "#fafbfc",
    textarea_border: "#e1e4e8",
    textarea_focus_border: "#0366d6",
    textarea_text: "#586069",
    tab_border: "#e1e4e8",
    tab_bg: "#f6f8fa",
    tab_selected_bg: "#ffffff",
    tab_container_gb: "#ffffff",
    border_primary: "#e1e4e8",
    register_btn: "rgb(46, 154, 254)",
    register_btn_disabled: "rgba(46, 154, 254, 0.5)",
    loading_dots: "#d8d8d8",
    sidemenu_hover: "#2e9afe",
    sidemenu_default: "#6e6e6e",
    header_bg: "#24292e",
    header_title_text: "#ffffff",
    header_dropmenu_bg: "#ffffff",
    header_dropmenu_hover_bg: "#0366d6",
    header_dropmenu_text: "#1b1f23",
    header_dropmenu_hover_text: "#ffffff",
    header_dropmenu_boader: "#e1e4e8",
    header_dropmenu_modal_bg: "transparent",
    caret_text: "#ffffff",
    main_bg: "#ffffff",
    signup_box_border: "#e6e6e6",
    signup_submit_disabled: "rgb(164, 164, 164, 0.5)",
    signup_submit: "rgb(164, 164, 164)",
    signup_container: "white",
    form_warning_msg: "red",
    signup_page_bg: "#f2f2f2",
    signup_submit_text: "white",
    issue_drop_btn: "#6a737d",
    issue_drop_hover_btn: "#444d56",
    issue_drop_modal_bg: "transparent",
    issue_item_title: "#0366d6",
    issue_item_detail_info_text: "#6a737d",
    issue_item_milestone_title: "#6a737d",
    list_group_header_border: "#eaecef",
    list_group_header_bg: "#f6f8fa",
    list_group_item_bg: "#ffffff",
    list_group_item_hover_bg: "#f6f8fa",
    list_group_border: "#eaecef",
    container_border: "#e1e4e8",
    title_input_bg: "#fafbfc",
    title_input_border: "#e1e4e8",
    title_input_focus_border: "#0366d6",
    filterbar_menu_bg: "#f6f8fa",
    filterbar_menu_input_text: "#444d56",
    filterbar_menu_input_bg: "#F6F8FA",
    filterbar_menu_btn_text: "#444d56",
    filterbar_menu_border: "#e1e4e8",
    filterbar_dropmenu_text: "#444d56",
    page_nav_btn_text: "#444d56",
    page_nav_btn_bg: "#ffffff",
    page_nav_btn_hover_bg: "#f6f8fa",
    list_group_border: "#eaecef",
    primary_hover_bg: "#f3f4f6",
    tertiary_border: "#d1d5da",
    tertiary_bg: "#f6f8fa"
};

export { color };
